repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-case-conflict
    -   id: check-illegal-windows-names
    -   id: detect-private-key
    -   id: check-yaml
    -   id: fix-byte-order-marker
    -   id: mixed-line-ending
        args: [--fix, 'lf']

-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-tabs  # Replace tabs by whitespaces
        args: [--whitespaces-count, '2']
